;METADATA=(Diff=true, UseCommands=true)
[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=7D403C5A478CCBA26B25A5913A982854
bStartInVR=True

[/Script/LootLockerSDK.LootLockerConfig]
OutdatedSDKWarning="This version of LootLocker is no longer updated through fab because of fab guidelines. Please use GitHub releases to update: https://github.com/lootlocker/unreal-sdk/releases"
LootLockerGameKey=dev_b2704f41687f4bf1908efc9d042d41fc
GameVersion=1.0
InvalidGameVersionWarning="Game version needs to follow a numeric Semantic Versioning pattern: X.Y.Z.B with the sections denoting MAJOR.MINOR.PATCH.BUILD and the last two being optional. Read more at https://docs.lootlocker.com/the-basics/core-concepts/glossary#game-version"
AllowTokenRefresh=True
DomainKey=4launo2d
LogOutsideOfEditor=False
LootLockerLogLevel=Warning
bEnableFileLogging=False
LogFileName=LootLockerLog
LongLogFilePath=
bEnablePresence=False
bEnablePresenceAutoConnect=True
bEnablePresenceAutoDisconnectOnFocusChange=True
bEnablePresenceInEditor=True
IsValidGameVersion=True
IsOutdatedSDK=False

